"use client";
import './styles/HexagonBackground.css'
import { useCallback } from 'react'
import Particles from 'react-particles';
import { loadSlim } from "tsparticles-slim";
const HexagonBackground = () => {
    const particlesInit = useCallback(async engine => {
        console.log(engine);
        // you can initiate the tsParticles instance (engine) here, adding custom shapes or presets
        // this loads the tsparticles package bundle, it's the easiest method for getting everything ready
        // starting from v2 you can add only the features you need reducing the bundle size
        //await loadFull(engine);
        await loadSlim(engine);
    }, []);

    const particlesLoaded = useCallback(async container => {
        await console.log(container);
    }, []);
  return (
    <div className='hexagon-background'>
         <Particles
            id="tsparticles"
            init={particlesInit}
            loaded={particlesLoaded}
            options={{
                background: {
                    color: {
                        value: "#00000",
                    },
                },
                fpsLimit: 120,
                interactivity: {
                    events: {
                        onClick: {
                            enable: true,
                            mode: "push",
                        },
                        onHover: {
                            enable: true,
                            mode: "grab",
                        },
                        resize: true,
                    },
                    modes: {
                        push: {
                            quantity: 2,
                        },
                        repulse: {
                            distance: 200,
                            duration: 0.4,
                        },
                    },
                },
                particles: {
                    color: {
                        value: "#ffffff",
                    },
                    links: {
                        color: "#ffffff",
                        distance: 150,
                        enable: false,
                        opacity: 0.5,
                        width: 1,
                    },
                    move: {
                        direction: "none",
                        enable: true,
                        outModes: {
                            default: "bounce",
                        },
                        random: false,
                        speed: 1,
                        straight: false,
                    },
                    number: {
                        density: {
                            enable: true,
                            area: 800,
                        },
                        value: 80,
                    },
                    opacity: {
                        value: 0.2,
                    },
                    shape: {
                        type: "circle",
                    },
                    size: {
                        value: { min: 1, max: 5 },
                    },
                },
                detectRetina: true,
            }}
        />

        <div className='-z-50'>
        <div className='row'>
            <div className="hexagon"></div>
            <div className="hexagon"></div>
            <div className="hexagon"></div>
            <div className="hexagon"></div>
            <div className="hexagon"></div>
            <div className="hexagon"></div>
            <div className="hexagon"></div>
            <div className="hexagon"></div>
            <div className="hexagon"></div>
            <div className="hexagon"></div>
            <div className="hexagon"></div>
            <div className="hexagon"></div>
            <div className="hexagon"></div>
            <div className="hexagon"></div>
            <div className="hexagon"></div>
            <div className="hexagon"></div>
            <div className="hexagon"></div>
            <div className="hexagon"></div>
            <div className="hexagon"></div>
            <div className="hexagon"></div>
            <div className="hexagon"></div>
            <div className="hexagon"></div>
            <div className="hexagon"></div>
            <div className="hexagon"></div>
            <div className="hexagon"></div>
            <div className="hexagon"></div>
            <div className="hexagon"></div>
            <div className="hexagon"></div>
            <div className="hexagon"></div>
            <div className="hexagon"></div>
            <div className="hexagon"></div>
            <div className="hexagon"></div>
        </div>
        <div className='row'>
            <div className="hexagon"></div>
            <div className="hexagon"></div>
            <div className="hexagon"></div>
            <div className="hexagon"></div>
            <div className="hexagon"></div>
            <div className="hexagon"></div>
            <div className="hexagon"></div>
            <div className="hexagon"></div>
            <div className="hexagon"></div>
            <div className="hexagon"></div>
            <div className="hexagon"></div>
            <div className="hexagon"></div>
            <div className="hexagon"></div>
            <div className="hexagon"></div>
            <div className="hexagon"></div>
            <div className="hexagon"></div>
            <div className="hexagon"></div>
            <div className="hexagon"></div>
            <div className="hexagon"></div>
            <div className="hexagon"></div>
            <div className="hexagon"></div>
            <div className="hexagon"></div>
            <div className="hexagon"></div>
            <div className="hexagon"></div>
            <div className="hexagon"></div>
            <div className="hexagon"></div>
            <div className="hexagon"></div>
            <div className="hexagon"></div>
            <div className="hexagon"></div>
            <div className="hexagon"></div>
            <div className="hexagon"></div>
            <div className="hexagon"></div>
        </div>
        <div className='row'>
            <div className="hexagon"></div>
            <div className="hexagon"></div>
            <div className="hexagon"></div>
            <div className="hexagon"></div>
            <div className="hexagon"></div>
            <div className="hexagon"></div>
            <div className="hexagon"></div>
            <div className="hexagon"></div>
            <div className="hexagon"></div>
            <div className="hexagon"></div>
            <div className="hexagon"></div>
            <div className="hexagon"></div>
            <div className="hexagon"></div>
            <div className="hexagon"></div>
            <div className="hexagon"></div>
            <div className="hexagon"></div>
            <div className="hexagon"></div>
            <div className="hexagon"></div>
            <div className="hexagon"></div>
            <div className="hexagon"></div>
            <div className="hexagon"></div>
            <div className="hexagon"></div>
            <div className="hexagon"></div>
            <div className="hexagon"></div>
            <div className="hexagon"></div>
            <div className="hexagon"></div>
            <div className="hexagon"></div>
            <div className="hexagon"></div>
            <div className="hexagon"></div>
            <div className="hexagon"></div>
            <div className="hexagon"></div>
            <div className="hexagon"></div>
        </div>
        <div className='row'>
            <div className="hexagon"></div>
            <div className="hexagon"></div>
            <div className="hexagon"></div>
            <div className="hexagon"></div>
            <div className="hexagon"></div>
            <div className="hexagon"></div>
            <div className="hexagon"></div>
            <div className="hexagon"></div>
            <div className="hexagon"></div>
            <div className="hexagon"></div>
            <div className="hexagon"></div>
            <div className="hexagon"></div>
            <div className="hexagon"></div>
            <div className="hexagon"></div>
            <div className="hexagon"></div>
            <div className="hexagon"></div>
            <div className="hexagon"></div>
            <div className="hexagon"></div>
            <div className="hexagon"></div>
            <div className="hexagon"></div>
            <div className="hexagon"></div>
            <div className="hexagon"></div>
            <div className="hexagon"></div>
            <div className="hexagon"></div>
            <div className="hexagon"></div>
            <div className="hexagon"></div>
            <div className="hexagon"></div>
            <div className="hexagon"></div>
            <div className="hexagon"></div>
            <div className="hexagon"></div>
            <div className="hexagon"></div>
            <div className="hexagon"></div>
        </div>
        <div className='row'>
            <div className="hexagon"></div>
            <div className="hexagon"></div>
            <div className="hexagon"></div>
            <div className="hexagon"></div>
            <div className="hexagon"></div>
            <div className="hexagon"></div>
            <div className="hexagon"></div>
            <div className="hexagon"></div>
            <div className="hexagon"></div>
            <div className="hexagon"></div>
            <div className="hexagon"></div>
            <div className="hexagon"></div>
            <div className="hexagon"></div>
            <div className="hexagon"></div>
            <div className="hexagon"></div>
            <div className="hexagon"></div>
            <div className="hexagon"></div>
            <div className="hexagon"></div>
            <div className="hexagon"></div>
            <div className="hexagon"></div>
            <div className="hexagon"></div>
            <div className="hexagon"></div>
            <div className="hexagon"></div>
            <div className="hexagon"></div>
            <div className="hexagon"></div>
            <div className="hexagon"></div>
            <div className="hexagon"></div>
            <div className="hexagon"></div>
            <div className="hexagon"></div>
            <div className="hexagon"></div>
            <div className="hexagon"></div>
            <div className="hexagon"></div>
        </div>
        <div className='row'>
            <div className="hexagon"></div>
            <div className="hexagon"></div>
            <div className="hexagon"></div>
            <div className="hexagon"></div>
            <div className="hexagon"></div>
            <div className="hexagon"></div>
            <div className="hexagon"></div>
            <div className="hexagon"></div>
            <div className="hexagon"></div>
            <div className="hexagon"></div>
            <div className="hexagon"></div>
            <div className="hexagon"></div>
            <div className="hexagon"></div>
            <div className="hexagon"></div>
            <div className="hexagon"></div>
            <div className="hexagon"></div>
            <div className="hexagon"></div>
            <div className="hexagon"></div>
            <div className="hexagon"></div>
            <div className="hexagon"></div>
            <div className="hexagon"></div>
            <div className="hexagon"></div>
            <div className="hexagon"></div>
            <div className="hexagon"></div>
            <div className="hexagon"></div>
            <div className="hexagon"></div>
            <div className="hexagon"></div>
            <div className="hexagon"></div>
            <div className="hexagon"></div>
            <div className="hexagon"></div>
            <div className="hexagon"></div>
            <div className="hexagon"></div>
        </div>
        <div className='row'>
            <div className="hexagon"></div>
            <div className="hexagon"></div>
            <div className="hexagon"></div>
            <div className="hexagon"></div>
            <div className="hexagon"></div>
            <div className="hexagon"></div>
            <div className="hexagon"></div>
            <div className="hexagon"></div>
            <div className="hexagon"></div>
            <div className="hexagon"></div>
            <div className="hexagon"></div>
            <div className="hexagon"></div>
            <div className="hexagon"></div>
            <div className="hexagon"></div>
            <div className="hexagon"></div>
            <div className="hexagon"></div>
            <div className="hexagon"></div>
            <div className="hexagon"></div>
            <div className="hexagon"></div>
            <div className="hexagon"></div>
            <div className="hexagon"></div>
            <div className="hexagon"></div>
            <div className="hexagon"></div>
            <div className="hexagon"></div>
            <div className="hexagon"></div>
            <div className="hexagon"></div>
            <div className="hexagon"></div>
            <div className="hexagon"></div>
            <div className="hexagon"></div>
            <div className="hexagon"></div>
            <div className="hexagon"></div>
            <div className="hexagon"></div>
        </div>
        <div className='row'>
            <div className="hexagon"></div>
            <div className="hexagon"></div>
            <div className="hexagon"></div>
            <div className="hexagon"></div>
            <div className="hexagon"></div>
            <div className="hexagon"></div>
            <div className="hexagon"></div>
            <div className="hexagon"></div>
            <div className="hexagon"></div>
            <div className="hexagon"></div>
            <div className="hexagon"></div>
            <div className="hexagon"></div>
            <div className="hexagon"></div>
            <div className="hexagon"></div>
            <div className="hexagon"></div>
            <div className="hexagon"></div>
            <div className="hexagon"></div>
            <div className="hexagon"></div>
            <div className="hexagon"></div>
            <div className="hexagon"></div>
            <div className="hexagon"></div>
            <div className="hexagon"></div>
            <div className="hexagon"></div>
            <div className="hexagon"></div>
            <div className="hexagon"></div>
            <div className="hexagon"></div>
            <div className="hexagon"></div>
            <div className="hexagon"></div>
            <div className="hexagon"></div>
            <div className="hexagon"></div>
            <div className="hexagon"></div>
            <div className="hexagon"></div>
        </div>
        <div className='row'>
            <div className="hexagon"></div>
            <div className="hexagon"></div>
            <div className="hexagon"></div>
            <div className="hexagon"></div>
            <div className="hexagon"></div>
            <div className="hexagon"></div>
            <div className="hexagon"></div>
            <div className="hexagon"></div>
            <div className="hexagon"></div>
            <div className="hexagon"></div>
            <div className="hexagon"></div>
            <div className="hexagon"></div>
            <div className="hexagon"></div>
            <div className="hexagon"></div>
            <div className="hexagon"></div>
            <div className="hexagon"></div>
            <div className="hexagon"></div>
            <div className="hexagon"></div>
            <div className="hexagon"></div>
            <div className="hexagon"></div>
            <div className="hexagon"></div>
            <div className="hexagon"></div>
            <div className="hexagon"></div>
            <div className="hexagon"></div>
            <div className="hexagon"></div>
            <div className="hexagon"></div>
            <div className="hexagon"></div>
            <div className="hexagon"></div>
            <div className="hexagon"></div>
            <div className="hexagon"></div>
            <div className="hexagon"></div>
            <div className="hexagon"></div>
        </div>
        <div className='row'>
            <div className="hexagon"></div>
            <div className="hexagon"></div>
            <div className="hexagon"></div>
            <div className="hexagon"></div>
            <div className="hexagon"></div>
            <div className="hexagon"></div>
            <div className="hexagon"></div>
            <div className="hexagon"></div>
            <div className="hexagon"></div>
            <div className="hexagon"></div>
            <div className="hexagon"></div>
            <div className="hexagon"></div>
            <div className="hexagon"></div>
            <div className="hexagon"></div>
            <div className="hexagon"></div>
            <div className="hexagon"></div>
            <div className="hexagon"></div>
            <div className="hexagon"></div>
            <div className="hexagon"></div>
            <div className="hexagon"></div>
            <div className="hexagon"></div>
            <div className="hexagon"></div>
            <div className="hexagon"></div>
            <div className="hexagon"></div>
            <div className="hexagon"></div>
            <div className="hexagon"></div>
            <div className="hexagon"></div>
            <div className="hexagon"></div>
            <div className="hexagon"></div>
            <div className="hexagon"></div>
            <div className="hexagon"></div>
            <div className="hexagon"></div>
        </div>
        <div className='row'>
            <div className="hexagon"></div>
            <div className="hexagon"></div>
            <div className="hexagon"></div>
            <div className="hexagon"></div>
            <div className="hexagon"></div>
            <div className="hexagon"></div>
            <div className="hexagon"></div>
            <div className="hexagon"></div>
            <div className="hexagon"></div>
            <div className="hexagon"></div>
            <div className="hexagon"></div>
            <div className="hexagon"></div>
            <div className="hexagon"></div>
            <div className="hexagon"></div>
            <div className="hexagon"></div>
            <div className="hexagon"></div>
            <div className="hexagon"></div>
            <div className="hexagon"></div>
            <div className="hexagon"></div>
            <div className="hexagon"></div>
            <div className="hexagon"></div>
            <div className="hexagon"></div>
            <div className="hexagon"></div>
            <div className="hexagon"></div>
            <div className="hexagon"></div>
            <div className="hexagon"></div>
            <div className="hexagon"></div>
            <div className="hexagon"></div>
            <div className="hexagon"></div>
            <div className="hexagon"></div>
            <div className="hexagon"></div>
            <div className="hexagon"></div>
        </div>
        <div className='row'>
            <div className="hexagon"></div>
            <div className="hexagon"></div>
            <div className="hexagon"></div>
            <div className="hexagon"></div>
            <div className="hexagon"></div>
            <div className="hexagon"></div>
            <div className="hexagon"></div>
            <div className="hexagon"></div>
            <div className="hexagon"></div>
            <div className="hexagon"></div>
            <div className="hexagon"></div>
            <div className="hexagon"></div>
            <div className="hexagon"></div>
            <div className="hexagon"></div>
            <div className="hexagon"></div>
            <div className="hexagon"></div>
            <div className="hexagon"></div>
            <div className="hexagon"></div>
            <div className="hexagon"></div>
            <div className="hexagon"></div>
            <div className="hexagon"></div>
            <div className="hexagon"></div>
            <div className="hexagon"></div>
            <div className="hexagon"></div>
            <div className="hexagon"></div>
            <div className="hexagon"></div>
            <div className="hexagon"></div>
            <div className="hexagon"></div>
            <div className="hexagon"></div>
            <div className="hexagon"></div>
            <div className="hexagon"></div>
            <div className="hexagon"></div>
        </div>
        <div className='row'>
            <div className="hexagon"></div>
            <div className="hexagon"></div>
            <div className="hexagon"></div>
            <div className="hexagon"></div>
            <div className="hexagon"></div>
            <div className="hexagon"></div>
            <div className="hexagon"></div>
            <div className="hexagon"></div>
            <div className="hexagon"></div>
            <div className="hexagon"></div>
            <div className="hexagon"></div>
            <div className="hexagon"></div>
            <div className="hexagon"></div>
            <div className="hexagon"></div>
            <div className="hexagon"></div>
            <div className="hexagon"></div>
            <div className="hexagon"></div>
            <div className="hexagon"></div>
            <div className="hexagon"></div>
            <div className="hexagon"></div>
            <div className="hexagon"></div>
            <div className="hexagon"></div>
            <div className="hexagon"></div>
            <div className="hexagon"></div>
            <div className="hexagon"></div>
            <div className="hexagon"></div>
            <div className="hexagon"></div>
            <div className="hexagon"></div>
            <div className="hexagon"></div>
            <div className="hexagon"></div>
            <div className="hexagon"></div>
            <div className="hexagon"></div>
        </div>
        <div className='row'>
            <div className="hexagon"></div>
            <div className="hexagon"></div>
            <div className="hexagon"></div>
            <div className="hexagon"></div>
            <div className="hexagon"></div>
            <div className="hexagon"></div>
            <div className="hexagon"></div>
            <div className="hexagon"></div>
            <div className="hexagon"></div>
            <div className="hexagon"></div>
            <div className="hexagon"></div>
            <div className="hexagon"></div>
            <div className="hexagon"></div>
            <div className="hexagon"></div>
            <div className="hexagon"></div>
            <div className="hexagon"></div>
            <div className="hexagon"></div>
            <div className="hexagon"></div>
            <div className="hexagon"></div>
            <div className="hexagon"></div>
            <div className="hexagon"></div>
            <div className="hexagon"></div>
            <div className="hexagon"></div>
            <div className="hexagon"></div>
            <div className="hexagon"></div>
            <div className="hexagon"></div>
            <div className="hexagon"></div>
            <div className="hexagon"></div>
            <div className="hexagon"></div>
            <div className="hexagon"></div>
            <div className="hexagon"></div>
            <div className="hexagon"></div>
        </div>
        <div className='row'>
            <div className="hexagon"></div>
            <div className="hexagon"></div>
            <div className="hexagon"></div>
            <div className="hexagon"></div>
            <div className="hexagon"></div>
            <div className="hexagon"></div>
            <div className="hexagon"></div>
            <div className="hexagon"></div>
            <div className="hexagon"></div>
            <div className="hexagon"></div>
            <div className="hexagon"></div>
            <div className="hexagon"></div>
            <div className="hexagon"></div>
            <div className="hexagon"></div>
            <div className="hexagon"></div>
            <div className="hexagon"></div>
            <div className="hexagon"></div>
            <div className="hexagon"></div>
            <div className="hexagon"></div>
            <div className="hexagon"></div>
            <div className="hexagon"></div>
            <div className="hexagon"></div>
            <div className="hexagon"></div>
            <div className="hexagon"></div>
            <div className="hexagon"></div>
            <div className="hexagon"></div>
            <div className="hexagon"></div>
            <div className="hexagon"></div>
            <div className="hexagon"></div>
            <div className="hexagon"></div>
            <div className="hexagon"></div>
            <div className="hexagon"></div>
        </div>
        <div className='row'>
            <div className="hexagon"></div>
            <div className="hexagon"></div>
            <div className="hexagon"></div>
            <div className="hexagon"></div>
            <div className="hexagon"></div>
            <div className="hexagon"></div>
            <div className="hexagon"></div>
            <div className="hexagon"></div>
            <div className="hexagon"></div>
            <div className="hexagon"></div>
            <div className="hexagon"></div>
            <div className="hexagon"></div>
            <div className="hexagon"></div>
            <div className="hexagon"></div>
            <div className="hexagon"></div>
            <div className="hexagon"></div>
            <div className="hexagon"></div>
            <div className="hexagon"></div>
            <div className="hexagon"></div>
            <div className="hexagon"></div>
            <div className="hexagon"></div>
            <div className="hexagon"></div>
            <div className="hexagon"></div>
            <div className="hexagon"></div>
            <div className="hexagon"></div>
            <div className="hexagon"></div>
            <div className="hexagon"></div>
            <div className="hexagon"></div>
            <div className="hexagon"></div>
            <div className="hexagon"></div>
            <div className="hexagon"></div>
            <div className="hexagon"></div>
        </div>
        <div className='row'>
            <div className="hexagon"></div>
            <div className="hexagon"></div>
            <div className="hexagon"></div>
            <div className="hexagon"></div>
            <div className="hexagon"></div>
            <div className="hexagon"></div>
            <div className="hexagon"></div>
            <div className="hexagon"></div>
            <div className="hexagon"></div>
            <div className="hexagon"></div>
            <div className="hexagon"></div>
            <div className="hexagon"></div>
            <div className="hexagon"></div>
            <div className="hexagon"></div>
            <div className="hexagon"></div>
            <div className="hexagon"></div>
            <div className="hexagon"></div>
            <div className="hexagon"></div>
            <div className="hexagon"></div>
            <div className="hexagon"></div>
            <div className="hexagon"></div>
            <div className="hexagon"></div>
            <div className="hexagon"></div>
            <div className="hexagon"></div>
            <div className="hexagon"></div>
            <div className="hexagon"></div>
            <div className="hexagon"></div>
            <div className="hexagon"></div>
            <div className="hexagon"></div>
            <div className="hexagon"></div>
            <div className="hexagon"></div>
            <div className="hexagon"></div>
        </div>
        <div className='row'>
            <div className="hexagon"></div>
            <div className="hexagon"></div>
            <div className="hexagon"></div>
            <div className="hexagon"></div>
            <div className="hexagon"></div>
            <div className="hexagon"></div>
            <div className="hexagon"></div>
            <div className="hexagon"></div>
            <div className="hexagon"></div>
            <div className="hexagon"></div>
            <div className="hexagon"></div>
            <div className="hexagon"></div>
            <div className="hexagon"></div>
            <div className="hexagon"></div>
            <div className="hexagon"></div>
            <div className="hexagon"></div>
            <div className="hexagon"></div>
            <div className="hexagon"></div>
            <div className="hexagon"></div>
            <div className="hexagon"></div>
            <div className="hexagon"></div>
            <div className="hexagon"></div>
            <div className="hexagon"></div>
            <div className="hexagon"></div>
            <div className="hexagon"></div>
            <div className="hexagon"></div>
            <div className="hexagon"></div>
            <div className="hexagon"></div>
            <div className="hexagon"></div>
            <div className="hexagon"></div>
            <div className="hexagon"></div>
            <div className="hexagon"></div>
        </div>
        <div className='row'>
            <div className="hexagon"></div>
            <div className="hexagon"></div>
            <div className="hexagon"></div>
            <div className="hexagon"></div>
            <div className="hexagon"></div>
            <div className="hexagon"></div>
            <div className="hexagon"></div>
            <div className="hexagon"></div>
            <div className="hexagon"></div>
            <div className="hexagon"></div>
            <div className="hexagon"></div>
            <div className="hexagon"></div>
            <div className="hexagon"></div>
            <div className="hexagon"></div>
            <div className="hexagon"></div>
            <div className="hexagon"></div>
            <div className="hexagon"></div>
            <div className="hexagon"></div>
            <div className="hexagon"></div>
            <div className="hexagon"></div>
            <div className="hexagon"></div>
            <div className="hexagon"></div>
            <div className="hexagon"></div>
            <div className="hexagon"></div>
            <div className="hexagon"></div>
            <div className="hexagon"></div>
            <div className="hexagon"></div>
            <div className="hexagon"></div>
            <div className="hexagon"></div>
            <div className="hexagon"></div>
            <div className="hexagon"></div>
            <div className="hexagon"></div>
        </div>
        <div className='row'>
            <div className="hexagon"></div>
            <div className="hexagon"></div>
            <div className="hexagon"></div>
            <div className="hexagon"></div>
            <div className="hexagon"></div>
            <div className="hexagon"></div>
            <div className="hexagon"></div>
            <div className="hexagon"></div>
            <div className="hexagon"></div>
            <div className="hexagon"></div>
            <div className="hexagon"></div>
            <div className="hexagon"></div>
            <div className="hexagon"></div>
            <div className="hexagon"></div>
            <div className="hexagon"></div>
            <div className="hexagon"></div>
            <div className="hexagon"></div>
            <div className="hexagon"></div>
            <div className="hexagon"></div>
            <div className="hexagon"></div>
            <div className="hexagon"></div>
            <div className="hexagon"></div>
            <div className="hexagon"></div>
            <div className="hexagon"></div>
            <div className="hexagon"></div>
            <div className="hexagon"></div>
            <div className="hexagon"></div>
            <div className="hexagon"></div>
            <div className="hexagon"></div>
            <div className="hexagon"></div>
            <div className="hexagon"></div>
            <div className="hexagon"></div>
        </div>
        <div className='row'>
            <div className="hexagon"></div>
            <div className="hexagon"></div>
            <div className="hexagon"></div>
            <div className="hexagon"></div>
            <div className="hexagon"></div>
            <div className="hexagon"></div>
            <div className="hexagon"></div>
            <div className="hexagon"></div>
            <div className="hexagon"></div>
            <div className="hexagon"></div>
            <div className="hexagon"></div>
            <div className="hexagon"></div>
            <div className="hexagon"></div>
            <div className="hexagon"></div>
            <div className="hexagon"></div>
            <div className="hexagon"></div>
            <div className="hexagon"></div>
            <div className="hexagon"></div>
            <div className="hexagon"></div>
            <div className="hexagon"></div>
            <div className="hexagon"></div>
            <div className="hexagon"></div>
            <div className="hexagon"></div>
            <div className="hexagon"></div>
            <div className="hexagon"></div>
            <div className="hexagon"></div>
            <div className="hexagon"></div>
            <div className="hexagon"></div>
            <div className="hexagon"></div>
            <div className="hexagon"></div>
            <div className="hexagon"></div>
            <div className="hexagon"></div>
        </div>
        <div className='row'>
            <div className="hexagon"></div>
            <div className="hexagon"></div>
            <div className="hexagon"></div>
            <div className="hexagon"></div>
            <div className="hexagon"></div>
            <div className="hexagon"></div>
            <div className="hexagon"></div>
            <div className="hexagon"></div>
            <div className="hexagon"></div>
            <div className="hexagon"></div>
            <div className="hexagon"></div>
            <div className="hexagon"></div>
            <div className="hexagon"></div>
            <div className="hexagon"></div>
            <div className="hexagon"></div>
            <div className="hexagon"></div>
            <div className="hexagon"></div>
            <div className="hexagon"></div>
            <div className="hexagon"></div>
            <div className="hexagon"></div>
            <div className="hexagon"></div>
            <div className="hexagon"></div>
            <div className="hexagon"></div>
            <div className="hexagon"></div>
            <div className="hexagon"></div>
            <div className="hexagon"></div>
            <div className="hexagon"></div>
            <div className="hexagon"></div>
            <div className="hexagon"></div>
            <div className="hexagon"></div>
            <div className="hexagon"></div>
            <div className="hexagon"></div>
        </div>
        <div className='row'>
            <div className="hexagon"></div>
            <div className="hexagon"></div>
            <div className="hexagon"></div>
            <div className="hexagon"></div>
            <div className="hexagon"></div>
            <div className="hexagon"></div>
            <div className="hexagon"></div>
            <div className="hexagon"></div>
            <div className="hexagon"></div>
            <div className="hexagon"></div>
            <div className="hexagon"></div>
            <div className="hexagon"></div>
            <div className="hexagon"></div>
            <div className="hexagon"></div>
            <div className="hexagon"></div>
            <div className="hexagon"></div>
            <div className="hexagon"></div>
            <div className="hexagon"></div>
            <div className="hexagon"></div>
            <div className="hexagon"></div>
            <div className="hexagon"></div>
            <div className="hexagon"></div>
            <div className="hexagon"></div>
            <div className="hexagon"></div>
            <div className="hexagon"></div>
            <div className="hexagon"></div>
            <div className="hexagon"></div>
            <div className="hexagon"></div>
            <div className="hexagon"></div>
            <div className="hexagon"></div>
            <div className="hexagon"></div>
            <div className="hexagon"></div>
        </div>
        </div>
        
        
    </div>
  )
}

export default HexagonBackground